//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectriTrackerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class skiTable
    {
        public string Nume { get; set; }
        public Nullable<double> Latitudine { get; set; }
        public Nullable<double> Longitudine { get; set; }
        public Nullable<int> Baterie { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Urgenta { get; set; }
        public string Telefon { get; set; }
        public Nullable<int> IsAdmin { get; set; }
        public Nullable<int> VitezaDepasita { get; set; }
        public Nullable<int> InAfaraRazei { get; set; }
        public int id { get; set; }
    }
}
